# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTU5OTZjZTBjYjI2OWRhZWY2ZjlhNmY3ZjRhZDI5ZjJmNGE2MmNjMTcxNTFiYmJjZDBmYmRjOGVkZWVjMWIwYjQ2MjVjZTA1MTgyMDA5NDUyZjA5M2MwMmQ1N2Q1ZDdkMWVmNzYyMDc4YTlhYjU3ZjJlYjI1NzdhOWMxMTk5NTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
